### ISSUE TITLE
PxMatrix controling

### ISSUE THREAD

**Issue by elektron95** [OLIMEX/ESP32-POE#10]
Hi, just a quick question,
As I have significantly less pins, how can I connect and control a PxMatrix 32X64 LED Matrix ?
It's using a HUB75 connection with the falling pins:

![Screenshot_20200305-062543](https://user-images.githubusercontent.com/61819102/75953872-3aaba480-5eaa-11ea-9a0f-15f07d933d1d.jpg)

Thank you for the help!

**Comment by DanKoloff** [comment]
Hello,

This is issue tracker for problems with the hardware design of ESP32-PoE. This is not the appropriate place to ask for advice. 

Please join the Olimex forums: https://www.olimex.com/forum/

For general advice related to ESP32 and ESP8266 make sure to also join the big espressif forums here (probably the English section): https://www.esp32.com/

Best regards,
Lub/OLIMEX
