### ISSUE TITLE
Changes for revision F & G missing from change log? 

### ISSUE THREAD

**Issue by glynhudson** [OLIMEX/ESP32-POE#22]
What's changed in the two latest revisions?

**Comment by DanKoloff** [comment]
There are no hardware revisions F and G of ESP32-POE yet... Maybe you meant to post this under ESP32-EVB repo?

**Comment by glynhudson** [comment]
Apologies, I was referring to the ESP32-GATEWAY. I've now found the hardware change log for this unit here:   https://github.com/OLIMEX/ESP32-GATEWAY/tree/master/HARDWARE
