### ISSUE TITLE
Discrepancy between readme, schematics, and example code

### ISSUE THREAD

**Issue by squintz** [OLIMEX/ESP32-POE#23]
ESP32-POE/SOFTWARE/ESP-IDF/ESP32_PoE_Ethernet_IDFv4.2/README.md

The Ethernet README says that a DM9051 will be used but when you look at the schematics (ESP32-PoE_Rev_E.pdf) a LAN8710A is shown. Furthermore, the example code has options for the DM9051 as well as other phys but does not have the LAN8710A listed. Instead it has the LAN8720A. I know these LAN chips are pretty much the same but when combined with the information in the README it makes it confusing.

**Comment by DanKoloff** [comment]
That's correct. It seems that our developer copy-pasted the default README from ESP-IDF and didn't change the text. I will change it to LAN8720 in the text. LAN8720 and LAN8710 are slightly different, 8710 can also work as 10Mbit/s and uses two pins more compared to 8720 that only works at max rate 100Mbit/s.
