### ISSUE TITLE
Alternatives for component LAN8710A-EZC ,SI3402-B-GM

### ISSUE THREAD

**Issue by mightChamp** [OLIMEX/ESP32-POE#25]
Hello,
I have followed your work, It helps me lot.
I need alternative solution for below components, mentioned in  ESP32-PoE_Rev_E.sch Doc:
1)  LAN8710A-EZC
2) SI3402-B-GM

Could you please suggest alternative for these?

Thank You

**Comment by TsvetanUsunov** [comment]
1. LAN8710A can be replaced by LAN8720
2. There are plenty of alternatives from MPS, Texas Instruments etc. For instance MP8007 or TPS23XXX
