### ISSUE TITLE
ESP32-PoE Rev. G alot of crc errors

### ISSUE THREAD

**Issue by Berjastein** [OLIMEX/ESP32-POE#27]
Hi, we have been using ESP32-PoE Rev. E without any problems.
Now we received Rev. G boards, and they give alot of crc errors.

We are running same code on Rev. E without any problems, i think its something with the power supply, from PoE.
Because if we run usb and ethernet it works without any problems.

Seems like the new poe is not working like the old one?
When a battery is charging it gets even worse.

Any advice on what to do?

**Comment by TsvetanUsunov** [comment]
contact support@olimex.com with description
