### ISSUE TITLE
Schematics for Revision "I"?

### ISSUE THREAD

**Issue by dfijma** [OLIMEX/ESP32-POE#28]
The HARDWARE-folder contains the schematics for revisions upto G1. Today, I received an ESP-POE board (ordered directly from Olimex) that shows "Revision I" (capital-i, I guess) on the PCB. Could the schematics for that revision also be made available?

**Comment by DanKoloff** [comment]
Thanks for the notice, should be available here now: https://github.com/OLIMEX/ESP32-POE/tree/master/HARDWARE
