### ISSUE TITLE
Problems with certain GPIOs

### ISSUE THREAD

**Issue by bmangodt** [OLIMEX/ESP32-POE#29]
I have designed a Raspberry Pi hat at work that has Wiegand, 4 external inputs and 3 relays with the function of it being used as an access control hat.
Now, I want the ESP32-POE to function with this instead of designing something from scratch, so I designed a simple adapter pcb for this. 
Everything works fine except 3 GPIOs. 
GPI 0, 1, 2 and 3 are connected to inputs 1, 2, 3 and 4 respectively. Only GPIO 0 and 3 are reading correctly, the other ones are floating.
Relay 3 is connected to GPI36. This GPIO stays in a high state even though it is configured as output and set low. 

All other GPIOS are configured in the exact same way and are behaving as they should. Also, according to the ESP32-POE pinout, all my chosen pins are available to use.
I cannot upload any schematic of the hat I designed as this is company property and is under NDA. I can however tell you all ports work on a Raspberry Pi. 

Also, steps to recreate aren't included because standard Arduino GPIO setup is straight forward and I'm only looking for why these specific GPIOs aren't behaving like they should. Are they used for something that is not mentioned? If so, then why are they available externally? Thanks in advance.

**Comment by DanKoloff** [comment]
GPI36 is not GPIO. It is only input for the board...
