### ISSUE TITLE
RevK Changelog

### ISSUE THREAD

**Issue by tube0013** [OLIMEX/ESP32-POE#35]
Just received a batch of RevK Boards. they appear 6mm longer than previous versions. Please post the rest of the changes in this version.

thanks.

**Comment by DanKoloff** [comment]
It is 5mm longer indeed, this is due to mount holes that are now available. Some other components had been moved too. Schematics, exports and notes had been updated, dimensions would take a little longer.

**Comment by DanKoloff** [comment]
Dimension picture is now also updated.
