### ISSUE TITLE
WifiEvent not being fired in sample code

### ISSUE THREAD

**Issue by bergerb-com** [OLIMEX/ESP32-POE#45]
https://github.com/OLIMEX/ESP32-POE/blob/master/SOFTWARE/ARDUINO/ESP32_PoE_Ethernet_Arduino/ESP32_PoE_Ethernet_Arduino.ino

I had to change all the SYSTEM_EVENT_ to ARDUINO_EVENT_ to get the WiFiEvent's to work.

**Comment by DanKoloff** [comment]
It doesn't happen here in our tests, we still can't figure out why it behaves differently.

**Comment by Stanimir-Petev** [comment]
The examples have being updated (both ESP32_PoE_Ethernet_Arduino and ESP32_PoE_Ethernet_SD_Card_Arduino). Not sure in which version of the package but Espressif decided to change these macros and broke quite a lot of our old examples (like these). Thanks for the feedback!
