### ISSUE TITLE
SD-Card "Card mount Failed!" in sample code

### ISSUE THREAD

**Issue by bergerb-com** [OLIMEX/ESP32-POE#46]
https://github.com/OLIMEX/ESP32-POE/blob/master/SOFTWARE/ARDUINO/ESP32_PoE_Ethernet_SD_Card_Arduino/ESP32_PoE_Ethernet_SD_Card_Arduino.ino

since the ESP32-POE has a 1-bit SD interface, would you be so kind and also include that in your sample code?

`SD_MMC.begin()`
needs to be
`SD_MMC.begin("/sdcard", true)`

without that line, the SD-Card wont mount.

**Comment by DanKoloff** [comment]
We tested it here and it seems to work fine. We have to reproduce the problem first before we can apply any changes or fixes. What card are you using (size and formatting)? What is the structure on the card? Which version of ESP32 package do you use, is it the latest one?

**Comment by bergerb-com** [comment]
FAT32, 64GB Card, reduced to 32GB
What do you mean by structure? There was no data on the card.
Do you mean your rev. by package? it neither works on rev. L or rev. K.
I am using PlatformIO, maybe that makes a difference?

**Comment by DanKoloff** [comment]
Yeah structure meant if you have folders or files or if it is blank.

Revision package meant package revision # in Arduino IDE.

We've used Arduino IDE and this sample code was made and tested in Arduino IDE. The folder with the example is named "ARDUINO".

Maybe it is related to PlatformIO and Arduino differences indeed.
